### ISSUE TITLE
build server

### ISSUE THREAD

**Issue by robertroeser** [rsocket/rsocket-go#18]
Hi,

Is there a third party build that you can setup for this? We have been using TravisCI for the other RSocket projects.

**Comment by jjeffcaii** [comment]
Hi,

In original repo, it used TravisCI for CI/DI. But I removed it because lack of unit test cases.

I've added a basic .travis.yml into repo. Please open TravisCI for it. Thanks!

// Jeffsky // ʕ•̫͡•ʔ-̫͡-ʕ•͓͡•ʔ-̫͡-ʕ•̫͡•ʔ
------------------------------------------
Wechat: jeffsky1024
Email: jjeffcaii@outlook.com
------------------------------------------

On Apr 17, 2019, 04:24 +0800, Robert Roeser <notifications@github.com>, wrote:

Hi,

Is there a third party build that you can setup for this? We have been using TravisCI for the other RSocket projects.
